#
# Artifacts Configuration - Orion-LD API Gateway
#
artifacts: []

containers:
  - name: orion-ld-gateway
    container-file: orion-ld/Dockerfile
    context: orion-ld
    platforms: linux/amd64,linux/arm64
    enable-slsa: true
    enable-sbom: true
    enable-scan: true
    labels:
      org.opencontainers.image.title: "Orion-LD API Gateway"
      org.opencontainers.image.description: "Secure API gateway for FIWARE Orion-LD with JWT authentication"
      org.opencontainers.image.vendor: "CTU-SematX"
